"""Standard HTTP 402 / payment proof header names."""

from __future__ import annotations

# Request / response metadata for agent-to-agent payments
PAYMENT_ADDRESS = "X-PAYMENT-ADDRESS"
PAYMENT_AMOUNT = "X-PAYMENT-AMOUNT"
PAYMENT_CURRENCY = "X-PAYMENT-CURRENCY"
PAYMENT_NETWORK = "X-PAYMENT-NETWORK"
PAYMENT_PROOF = "X-PAYMENT-PROOF"
PAYMENT_TX = "X-PAYMENT-TX"
PAYMENT_PROVIDER = "X-PAYMENT-PROVIDER"

ALL_REQUIREMENT_HEADERS = (
    PAYMENT_ADDRESS,
    PAYMENT_AMOUNT,
    PAYMENT_CURRENCY,
    PAYMENT_NETWORK,
)

ALL_PROOF_HEADERS = (
    PAYMENT_PROOF,
    PAYMENT_TX,
    PAYMENT_AMOUNT,
    PAYMENT_CURRENCY,
    PAYMENT_PROVIDER,
)
